# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
    # force all unspecified python hooks to run python3
    python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
      #    - id: check-yaml
    - id: check-added-large-files
    - id: check-json
    - id: check-merge-conflict
    - id: detect-aws-credentials
    - id: detect-private-key
    - id: mixed-line-ending
- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.12.0
  hooks:
    - id: commitizen
      stages: [commit-msg]
- repo: https://github.com/markdownlint/markdownlint
  rev: master
  hooks:
    - id: markdownlint_docker
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.4
  hooks:
    - id: shellcheck
      args:
      - -e
      - SC1072,SC1073
    - id: script-must-have-extension
    - id: script-must-not-have-extension
    - id: shfmt
      args:
      - -l
      - -i
      - "2"
      - -ci
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.9
  hooks:
    - id: forbid-tabs
      #    - id: insert-license
      #files: \.js$
      #args:
      #- --license-filepath
      #- COPYRIGHT
      #- --comment-style
      #- /*| *| */
        #    - id: insert-license
        # files: \.yaml$
        #args:
        #- --license-filepath
        #- COPYRIGHT
        #- --comment-style
        #- #
      #- repo: https://github.com/doublify/pre-commit-clang-format
      #  rev: master
      #  hooks:
      #    - id: clang-format
