#!/bin/bash

LABEL=$1
shift
COMMAND=$1
shift
clear
for pod in $(kubectl get pods -l "$LABEL" | grep -v Terminat | grep -v NAME | awk '{print $1}' | sort); do
  node_name=$(kubectl get pod "$pod" -o json | jq -r '.spec.nodeName')
  echo "=== $node_name $pod ==="
  kubectl "$COMMAND" "pod/$pod" "$@"
  echo
done
