#!/usr/bin/env bash
# Copyright © 2023 Kevin T. O'Donnell
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# shellcheck source=includer.sh
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include commands
@include k8s

LABEL=$1
shift
COMMAND=$1
shift
clear
for pod in $(k8s::ctl get pods -l "$LABEL" | grep -v Terminat |
  grep -v NAME | awk '{print $1}' | sort); do
  node_name=$(k8s::ctl get pod "$pod" -o json |
    $(commands::use jq) -r '.spec.nodeName')
  echo "=== $node_name $pod ==="
  k8s::ctl "$COMMAND" "pod/$pod" "$@"
  echo
done
