#!/bin/bash

# shellcheck disable=SC1090
source "$(dirname "$0")/include.sh"

addCliOptions
options::description "Scan an AWS account for all EKS clusters and write\
 their configurations to the local users config."
options::add -o p -d "node to migrate from" -a -e AWS_PROFILE
options::parse "$@"

if [ -n "${AWS_PROFILE}" ]; then
  INFO "Scanning ${AWS_PROFILE} for EKS clusters"
else
  INFO "Scanning default profile for EKS clusters"
fi

function get_clusters() {
  eksctl get clusters -A -o json -v 0
}

clusters="$(get_clusters)"
DEBUG "Found clusters: $clusters"
for c in $(echo "$clusters" | jq -r '.[].metadata |.name+"="+.region'); do
  cluster=$(echo "$c" | awk -F= '{print $1}')
  region=$(echo "$c" | awk -F= '{print $2}')
  INFO "Updating kubeconfig for $cluster in $region"
  exec::hide eksctl utils write-kubeconfig --cluster "$cluster" \
    --region "$region" || error_exit "Failed to update kubeconfig for $cluster"
done
