#!/usr/bin/env bash
# Copyright 2021 Blockchain Technology Partners
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# shellcheck source=includer.sh
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include commands
@include error
@include options

options::standard
options::add -o c -d "Config file for BB rest api" -a -m -e CONFIG
options::parse "$@"

shift $((OPTIND - 1))
if [ -n "$CONFIG" ] && [ -r "$HOME/.${CONFIG}-config" ]; then
  source "$HOME/.${CONFIG}-config"
else
  error::exit "Specified config($CONFIG) was not found"
fi

function ::curl() {
  $(commands::use curl) "$@"
}

function bb_api_call() {
  local method=$1
  local url=$2
  shift 2
  ::curl -s -X "$method" -u "$BB_USER:$BB_PAT" \
    "$BB_HOST/rest/api/latest/$url" "$@" | jq
}

function pr-data() {
  local repo="$1"
  local project repo
  project=$(echo "$repo" | awk -F/ '{print $1}')
  repo=$(echo "$repo" | awk -F/ '{print $2}')
  bb_api_call GET "projects/$project/repos/$repo/pull-requests?state=open&limit=100"
}

function pr-count() {
  local repo=$1
  pr-data "$repo" | jq -r '.size'
}

function pr-list() {
  local repo=$1
  pr-data "$repo" | jq -r '.values[].links.self[].href'
}

"$@"
