#!/bin/bash

# shellcheck disable=SC1090
source "$(dirname "$0")/include.sh"

addCliOptions
options::add -o c -d "Config file for BB rest api" -a -m -e CONFIG

options::parse "$@"

shift $((OPTIND - 1))
if [ -n "$CONFIG" ] && [ -r "$HOME/.${CONFIG}-config" ]; then
  source "$HOME/.${CONFIG}-config"
else
  error_exit "Specified config($CONFIG) was not found"
fi

function bb_api_call() {
  local method=$1
  local url=$2
  shift 2
  curl -s -X "$method" -u "$BB_USER:$BB_PAT" \
    "$BB_HOST/rest/api/latest/$url" "$@" | jq
}

function pr-data() {
  local repo="$1"
  local project repo
  project=$(echo "$repo" | awk -F/ '{print $1}')
  repo=$(echo "$repo" | awk -F/ '{print $2}')
  bb_api_call GET "projects/$project/repos/$repo/pull-requests?state=open&limit=100"
}

function pr-count() {
  local repo=$1
  pr-data "$repo" | jq -r '.size'
}

function pr-list() {
  local repo=$1
  pr-data "$repo" | jq -r '.values[].links.self[].href'
}

"$@"
