#!/bin/bash

# shellcheck disable=SC1090
source "$(dirname "$0")/include.sh"

addCliOptions
options::add -o l -d "add hyperlinks to commits" -x ADD_LINKS
options::parse "$@"

export GIT_PAGER=cat

function changelog::fromto() {
  local from to base_url
  from=${1:?}
  to=${2:?}
  base_url=${3}
  if [ "$ADD_LINKS" = "true" ] && [ -n "$base_url" ]; then
    git log "$from"..."$to" --no-merges --pretty=format:"* %s [view commit]($base_url/%H)"
  else
    git log "$from"..."$to" --no-merges --pretty=format:"* %s"
  fi
}

function changelog::full() {
  local later_tag=
  echo "# CHANGELOG"
  echo
  for tag in $(git::tagsinhistory); do
    if [ -z "$later_tag" ]; then
      later_tag="$tag"
      this_version=$(git describe --tags)
      if [ "$this_version" != "$tag" ]; then
        echo "## $this_version"
        echo
        changelog::fromto "$tag" "HEAD" "$(git::projecturl)"
        echo
        echo
      fi
    else
      echo "## $later_tag"
      echo
      changelog::fromto "$tag" "$later_tag" "$(git::projecturl)"
      echo
      echo
      later_tag="$tag"
    fi
  done
}

changelog::full
