#!/usr/bin/env bash
# shellcheck disable=SC1090
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include options
@include git

options::standard
options::add -o l -d "add hyperlinks to commits" -x ADD_LINKS
options::parse "$@"

export GIT_PAGER=cat

function ::fromto() {
  local from to base_url
  from=${1:?}
  to=${2:?}
  base_url=${3}
  if [ "$ADD_LINKS" = "true" ] && [ -n "$base_url" ]; then
    git::cmd log "$from"..."$to" --no-merges --pretty=format:"* %s [view commit]($base_url/%H)"
  else
    git::cmd log "$from"..."$to" --no-merges --pretty=format:"* %s"
  fi
}

function ::full() {
  local later_tag=
  echo "# CHANGELOG"
  echo
  for tag in $(git::tagsinhistory); do
    if [ -z "$later_tag" ]; then
      later_tag="$tag"
      this_version=$(git describe --tags)
      if [ "$this_version" != "$tag" ]; then
        echo "## $this_version"
        echo
        ::fromto "$tag" "HEAD" "$(git::projecturl)"
        echo
        echo
      fi
    else
      echo "## $later_tag"
      echo
      ::fromto "$tag" "$later_tag" "$(git::projecturl)"
      echo
      echo
      later_tag="$tag"
    fi
  done
}

::full
