#!/usr/bin/env bash
# shellcheck disable=SC1090
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include options
@include commands
@include log
@include exec
@include k8s

options::standard
options::set_description "Copies the keys from the validators to a directory \
  on the local host."
options::add -o l -d "label to select the validators" -a -m -e LABEL
options::parse "$@"

log::info "Copying keys from pods with label $LABEL"
for pod in $(k8s::ctl get pods -l "$LABEL" | grep -v NAME | awk '{print $1}' |
  sort); do
  node_name=$(k8s::ctl get pod "$pod" -o json | $(commands::use jq) -r '.spec.nodeName')
  log::info "Working on $node_name with pod $pod"
  mkdir -p "keys/$node_name"
  ln -s "$node_name" "keys/$pod"
  exec::capture k8s::ctl cp "$pod:/etc/sawtooth/keys/validator.priv" \
    "keys/$node_name/validator.priv" -c validator
  exec::capture k8s::ctl cp "$pod:/etc/sawtooth/keys/validator.pub" \
    "keys/$node_name/validaator.pub" -c validator
done
