#!/bin/bash

# shellcheck disable=SC1090
source "$(dirname "$0")/include.sh"

addCliOptions
options::description "Fetch the logs for the containers into local files"
options::add -o l -d "label of pod selector" -a -m -e selector
options::add -o c -d "container whose logs to dump" -a -m -e container
options::parse "$@"
shift $((OPTIND - 1))

get_pods_cmd=(kubectl get pods -l "$selector" -o json)
INFO "Fetching logs of pods for selector $selector container: ${container:?}"
for pod in $("${get_pods_cmd[@]}" |
  jq -r '.items[].metadata.name'); do
  log_cmd=(kubectl logs "$pod" "--tail=10000" --timestamps)
  if [ -n "$container" ]; then
    INFO "Fetching $container logs of pod $pod to $pod.$container.out"
    log_cmd+=(-c "$container")
  else
    INFO "Fetching all logs of pod $pod to $pod.$container.out"
    log_cmd+=(--all-containers "--max-log-requests=100")
  fi
  "${log_cmd[@]}" | sed 's/\x1b\[[0-9;]*m//g' >"$pod.$container.out"
done
