#!/usr/bin/env bash
# shellcheck source=includer.sh
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include options

options::description "This will pack the target script producing a new script\
 with no @include statements"
options::standard
options::add -o f -d "the script to pack" -a -m -e TargetFile
options::add -o o -d "output file" -a -m -e OutputFile
options::parse "$@"
shift "$((OPTIND - 1))"

function ::get_includes() {
  local file=${1:?}
  grep "@include" "$file" | awk '{print $NF}'
}

function get_all_includes() {
  local target=${1:?}
  declare -A checked

  scans_left="true"
  log::info "Scanning script ${target}"
  for inc in $(::get_includes "${target}"); do
    log::info "Adding $inc"
    checked[$inc]="false"
  done
  while [ "$scans_left" = "true" ]; do
    scans_left="false"
    for inc in "${!checked[@]}"; do
      if [ "${checked[$inc]}" = "false" ]; then
        for subinc in $(::get_includes "$(include::find $inc)"); do
          if [ -z "${checked[$subinc]}" ]; then
            log::info "Adding $subinc"
            checked[$subinc]="false"
            scans_left="true"
          fi
        done
        checked[$inc]="true"
      fi
    done
  done
  for inc in "${!checked[@]}"; do
    echo $inc
  done
}

set -e
echo "#!/usr/bin/env bash" >"${OutputFile:?}"
grep -v "^@include" "$(include::find doc)" |
  grep -v "includer.sh" |
  grep -v "^#!" >>"${OutputFile:?}"
grep -v "^@include" "$(include::find annotations)" |
  grep -v "includer.sh" |
  grep -v "^#!" >>"${OutputFile:?}"

for inc in $(get_all_includes "${TargetFile:?}"); do
  if [ "$inc" = "annotations" ]; then
    continue
  elif [ "$inc" = "doc" ]; then
    continue
  fi
  grep -v "^@include" "$(include::find "$inc")" |
    grep -v "includer.sh" |
    grep -v "^#!" >>"${OutputFile:?}"
done

grep -v "^@include" "${TargetFile}" |
  sed -e 's/BASH_SOURCE[\d]/BASH_SOURCE[0]/g' |
  grep -v "includer.sh" |
  grep -v "^#!" >>"${OutputFile:?}"

echo >>"${OutputFile:?}"

shfmt -i 2 -w "${OutputFile}"
