#!/bin/bash

# shellcheck disable=SC1090
source "$(dirname "$0")/include.sh"

addCliOptions
options::description "Opens a tmux session with panels for each of the pods\
 and containers specified running the provided command."
options::add -o l -d "label to select for the console" -a -m -e LABEL
options::add -o c -d "command to execute in the console" -a -m -e COMMAND
options::parse "$@"
shift $((OPTIND - 1))

SESSION=$LABEL

if tmux has-session -t "$SESSION"; then
  log::debug "Switch to session $SESSION"
  tmux switch-client -t "$SESSION"
else
  log::debug "Create session $SESSION"
  tmux new-session -s "$SESSION" -d
fi
WINDOW=$LABEL-$RANDOM
log::debug "Create and select window $WINDOW"
tmux new-window -n "$WINDOW"
tmux select-window -t "$WINDOW"
count=0
for pod in $(kubectl get pods -l "$LABEL" | grep -v Terminat | grep -v NAME | awk '{print $1}' | sort); do
  if [ "$count" -gt 0 ]; then
    log::debug "Split window on session $SESSION"
    tmux split-window -v -t "$SESSION"
  fi
  log::debug "Execute on $SESSION: kubectl $COMMAND pod/$pod $*"
  tmux send-keys -t "$SESSION" "kubectl $COMMAND pod/$pod $*" C-m
  log::debug "Tile window $WINDOW"
  tmux select-layout tiled
  count=$((count + 1))
done
