#!/bin/bash

RESOURCE_TYPE=$1
shift
for line in $(kubectl get "$RESOURCE_TYPE" --show-labels "$@" | awk '{print $1":"$NF}'); do
  resource_name=$(echo "$line" | awk -F: '{print $1}')
  labels=$(echo "$line" | awk -F: '{print $NF}')
  col1="$resource_name"
  for l in ${labels//,/ }; do
    printf "%-45.45s %-30s\n" "$col1" "$l"
  done
done
