#!/bin/bash

# shellcheck disable=SC1090
source "$(dirname "$0")/include.sh"

addCliOptions
options::description "prints out the resource name followed by its labels, one\
 per line."
options::add -o t -d "resource type to examine" -a -m -e RESOURCE_TYPE
options::parse "$@"
shift $((OPTIND - 1))

for line in $(kubectl get "$RESOURCE_TYPE" --show-labels "$@" | awk '{print $1":"$NF}'); do
  resource_name=$(echo "$line" | awk -F: '{print $1}')
  labels=$(echo "$line" | awk -F: '{print $NF}')
  col1="$resource_name"
  for l in ${labels//,/ }; do
    printf "%-45.45s %-30s\n" "$col1" "$l"
  done
done
