#!/usr/bin/env bash
# Copyright 2021 Blockchain Technology Partners
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

# shellcheck source=includer.sh
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include docker
@include error
@include exec
@include options

options::standard
options::description "Copy an image from one registry to another."
options::add -o f -d "source registry" -a -m -e HOST
options::add -o i -d "source image" -a -m -e IMAGE
options::add -o r -d "image tag" -a -m -e VERSION
options::add -o t -d "target repo" -a -m -e ARTIFACTORY
options::parse "$@"

exec::capture docker::cmd pull "$HOST/$IMAGE:$VERSION" ||
  error::exit "Failed to pull $HOST/$IMAGE:$VERSION"

exec::capture docker::cmd tag "$HOST/$IMAGE:$VERSION" \
  "$ARTIFACTORY/$IMAGE:$VERSION" ||
  error::exit "Failed to tag $ARTIFACTORY/$IMAGE:$VERSION"

exec::capture docker::cmd push "$ARTIFACTORY/$IMAGE:$VERSION" ||
  error::exit "Failed to push $ARTIFACTORY/$IMAGE:$VERSION"
