#!/bin/bash

# shellcheck disable=SC1090
source "$(dirname "$0")/include.sh"

addCliOptions
options::description "Switch all of the the branch of all of the target\
 repositories to the specified branch"
options::add -o c -d "client repository set" -a -e CLIENT
options::add -o o -d "target organization" -a -m -e ORG
options::add -o b -d "branch to switch to" -a -m -e BRANCH
options::parse "$@"
shift $((OPTIND - 1))

if [ -n "$CLIENT" ]; then
  TARGET_DIR="${HOME}/git/clients/${CLIENT}/${ORG}"
else
  TARGET_DIR="${HOME}/git/${ORG}"
fi

log::info "Scanning $TARGET_DIR"
for d in "$TARGET_DIR"/*; do
  log::info "Switching $d"
  if [ -d "$d/.git" ]; then
    if ! cd "$d"; then
      log::warn "Cannot cd to $d"
      continue
    fi
    if exec::hide git checkout -b "$BRANCH" "$@"; then
      log::info "Checked out $BRANCH in $d"
    else
      log::warn "Failed to checkout branch $BRANCH in $d"
    fi
    if ! cd - >/dev/null; then
      log::warn "Cannot cd back to OWD"
      continue
    fi
  else
    continue
  fi
done
