#!/bin/bash

# shellcheck disable=SC1090
source "$(dirname "$0")/include.sh"

addCliOptions
options::add -o t -d "target directory to examine and update" -a -m \
  -e TARGET_DIR
options::add -o b -d "proceed to bump minor version if breaking changes are found" \
  -x ALLOW_BREAKING

options::parse "$@"

pushd "$TARGET_DIR" >/dev/null || exit 1
LATEST_TAG=$(git describe --tags --match 'v*' --abbrev=0) || exit 1
LATEST_VERSION=$(echo "$LATEST_TAG" | cut -c2-)
BREAKING_CHANGES=$(git log "$LATEST_TAG"..HEAD | grep -c "BREAKING CHANGE")
CHANGES=$(git log "$LATEST_TAG"..HEAD | grep -c "^commit")

NOTICE "$LATEST_VERSION $CHANGES changes  $BREAKING_CHANGES breaks"

skip="true"
if [ "$BREAKING_CHANGES" -gt 0 ]; then
  if [ "${ALLOW_BREAKING}" = "true" ]; then
    TAG=$("${DIR}/semver" bump minor "$LATEST_VERSION")
    skip="false"
  else
    WARNING "Minor version changes due to breaking changes must be explicity allowed!"
    exit 1
  fi
elif [ "$CHANGES" -gt 0 ]; then
  TAG=$("${DIR}/semver" bump patch "$LATEST_VERSION")
  skip="false"
else
  TAG="$LATEST_VERSION"
  skip="true"
fi

TAG="v${TAG}"

if [ "$skip" = "false" ]; then
  NOTICE "Will tag as $TAG"
  git tag -a -s "$TAG" -m "Auto Tagging $TAG"
fi
popd || exit 0
