#!/usr/bin/env bash
# shellcheck disable=SC1090
source "$(dirname "${BASH_SOURCE[0]}")/includer.sh"

@include options
@include log
@include git

options::standard
options::description "Add a new tag to the repository based on semver and\
 conventional commits."
options::add -o t -d "target directory to examine and update" -a -m \
  -e TARGET_DIR
options::add -o p -d "Patch tag" \
  -x PATCH_TAG
options::add -o n -d "Don't annotate tag" \
  -x DONT_ANNOTATE_TAG
options::add -o b -d "proceed to bump minor version if breaking changes are found" \
  -x ALLOW_BREAKING
options::parse "$@"

pushd "$TARGET_DIR" >/dev/null || exit 1
LATEST_TAG=$(git::cmd describe --tags --match 'v*' --abbrev=0) || exit 1
LATEST_VERSION=$(echo "$LATEST_TAG" | cut -c2-)
BREAKING_CHANGES=$(git::cmd log "$LATEST_TAG"..HEAD | grep -c "BREAKING CHANGE")
CHANGES=$(git::cmd log "$LATEST_TAG"..HEAD | grep -c "^commit")

log::notice "$LATEST_VERSION $CHANGES changes  $BREAKING_CHANGES breaks"

skip="true"
if [ "$BREAKING_CHANGES" -gt 0 ]; then
  if [ "${ALLOW_BREAKING}" = "true" ]; then
    TAG=$("${DIR}/semver" bump minor "$LATEST_VERSION")
    skip="false"
  else
    log::warn "Minor version changes due to breaking changes must be explicity allowed!"
    exit 1
  fi
elif [ "$CHANGES" -gt 0 ]; then
  TAG=$("${DIR}/semver" bump patch "$LATEST_VERSION")
  skip="false"
else
  TAG="$LATEST_VERSION"
  skip="true"
fi

TAG="v${TAG}"

if [ "$skip" = "false" ]; then
  log::notice "Will tag as $TAG"
  if [ "$DONT_ANNOTATE_TAG" = "true" ]; then
    git::cmd tag "$TAG"
  else
    git::cmd tag -a -s "$TAG" -m "Auto Tagging $TAG"
  fi
fi
popd || exit 0
